version: '3.8'

services:
  youtube-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./config.ini:/app/config.ini:ro
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped